version: '3.8'

networks:
  wise_network:
    driver: "bridge"

services:
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: wise
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wise_network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: order_receiver_wise_backend
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "8082:8082"
    networks:
      - wise_network