spring.application.name=order-receiver
client.service.url=http://wise-client-service:8080/clientes
product.service.url=http://wise-product-service:8080

# RabbitMQ
spring.rabbitmq.host=wise-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=wise
spring.rabbitmq.password=admin